/**
 * Tours guiados didáticos passo a passo (F1.8).
 * Lote inicial de 6 tours anatômicos com câmera, camadas e explicações clínicas integradas.
 */

export const TOURS = [
  {
    id: 'manguito',
    title: 'Manguito Rotador',
    subtitle: 'Estabilidade dinâmica e mobilidade do ombro',
    region: 'membro_sup',
    steps: [
      {
        title: 'Visão Geral do Manguito Rotador',
        text: 'O manguito rotador é formado por quatro músculos que abraçam a cabeça do úmero, estabilizando-a na cavidade glenoidal da escápula: supraespinhal, infraespinhal, redondo menor e subescapular.',
        dissect: 2,
        region: 'membro_sup',
        highlight: 'deltoide',
        cam: { pos: [2.5, 0.4, 5.2], target: [1.2, -0.6, 0.2] },
      },
      {
        title: 'Músculo Supraespinhal',
        text: 'Origina-se na fossa supraespinhal da escápula e insere-se na faceta superior do tubérculo maior do úmero. Inicia a abdução do braço (primeiros 15°) e é o tendão mais acometido por tendinites e rupturas por compressão no arco coracoacromial.',
        dissect: 3,
        region: 'membro_sup',
        highlight: 'supraespinhal',
        cam: { pos: [2.0, 0.6, 4.0], target: [1.3, -0.5, 0.0] },
      },
      {
        title: 'Músculo Infraespinhal',
        text: 'Ocupa a fossa infraespinhal e fixa-se na faceta média do tubérculo maior. É o principal rotador lateral do braço. Inervado pelo nervo supraescapular (C5, C6).',
        dissect: 3,
        region: 'membro_sup',
        highlight: 'infraespinhal',
        cam: { pos: [1.6, 0.2, -4.5], target: [1.3, -0.6, 0.0] },
      },
      {
        title: 'Músculo Redondo Menor',
        text: 'Pequeno músculo tubular abaixo do infraespinhal. Realiza rotação lateral e adução fraca do braço. Diferencia-se por ser inervado pelo nervo axilar (C5, C6).',
        dissect: 3,
        region: 'membro_sup',
        highlight: 'redondo_menor',
        cam: { pos: [2.0, -0.2, -4.0], target: [1.3, -0.7, 0.0] },
      },
      {
        title: 'Músculo Subescapular',
        text: 'Ocupa toda a fossa subescapular (face anterior da escápula) e insere-se no tubérculo menor do úmero. É um poderoso rotador medial e adutor do braço, inervado pelos nervos subescapulares superior e inferior.',
        dissect: 4,
        region: 'membro_sup',
        highlight: 'subescapular',
        cam: { pos: [1.8, 0.1, 4.2], target: [1.2, -0.8, 0.1] },
      },
    ],
  },
  {
    id: 'plexo_braquial',
    title: 'Plexo Braquial',
    subtitle: 'Origem e distribuição da inervação do membro superior',
    region: 'membro_sup',
    steps: [
      {
        title: 'Formação das Raízes (C5–T1)',
        text: 'O plexo braquial é formado pelos ramos ventrais dos nervos espinais C5 a T1. Emerge no pescoço entre os músculos escalenos anterior e médio (trígono interescalênico).',
        dissect: 4,
        region: 'membro_sup',
        highlight: 'n_musculocutaneo',
        cam: { pos: [1.8, -0.1, 4.5], target: [0.8, -1.2, 0.2] },
      },
      {
        title: 'Troncos e Fascículos',
        text: 'As raízes unem-se em três troncos (superior, médio e inferior) que cruzam a clavícula, dividem-se em divisões anteriores e posteriores e formam os fascículos lateral, medial e posterior ao redor da artéria axilar.',
        dissect: 4,
        region: 'membro_sup',
        highlight: 'n_mediano',
        cam: { pos: [2.0, -0.5, 4.0], target: [1.2, -1.5, 0.3] },
      },
      {
        title: 'Ramos Terminais Principais',
        text: 'Origina os cinco grandes nervos terminais: Musculocutâneo (flexores do braço), Axilar (deltoide e redondo menor), Radial (extensores do membro), Mediano (flexores do antebraço e eminência tenar) e Ulnar (intrínsecos da mão).',
        dissect: 4,
        region: 'membro_sup',
        highlight: 'n_radial',
        cam: { pos: [2.2, -1.0, 4.5], target: [1.4, -2.0, 0.2] },
      },
    ],
  },
  {
    id: 'nervo_radial',
    title: 'Nervo Radial e Extensores',
    subtitle: 'Trajeto no sulco espiral e controle da extensão',
    region: 'membro_sup',
    steps: [
      {
        title: 'Origem e Sulco do Nervo Radial',
        text: 'Maior ramo do fascículo posterior (C5–T1). Contorna o úmero posteriormente no sulco do nervo radial, acompanhado pela artéria braquial profunda, passando entre as cabeças lateral e medial do tríceps braquial.',
        dissect: 4,
        region: 'membro_sup',
        highlight: 'n_radial',
        cam: { pos: [1.8, -0.5, -4.5], target: [1.5, -1.8, 0.0] },
      },
      {
        title: 'Tríceps Braquial',
        text: 'Inervado pelo nervo radial antes de passar o cotovelo. Suas três cabeças (longa, lateral e medial) convergem para o olécrano da ulna, sendo o principal extensor do antebraço.',
        dissect: 3,
        region: 'membro_sup',
        highlight: 'triceps_lateral',
        cam: { pos: [2.2, -1.0, -3.8], target: [1.6, -1.9, 0.0] },
      },
      {
        title: 'Divisão no Antebraço: Ramos Profundo e Superficial',
        text: 'No cotovelo anterior, divide-se em ramo profundo (motor, atravessa o supinador como nervo interósseo posterior para os extensores de punho e dedos) e ramo superficial (puramente sensitivo para o dorso da mão).',
        dissect: 4,
        region: 'membro_sup',
        highlight: 'braquiorradial',
        cam: { pos: [2.4, -1.8, 3.2], target: [1.8, -2.5, 0.2] },
      },
      {
        title: 'Correlação Clínica: "Queda do Punho"',
        text: 'Fraturas da diáfise umeral ou compressão prolongada do nervo radial ("paralisia de sábado à noite") causam paralisia dos extensores do punho e dos dedos, resultando na mão caída.',
        dissect: 3,
        region: 'membro_sup',
        highlight: 'extensor_radial_longo',
        cam: { pos: [2.5, -2.2, 2.5], target: [2.0, -2.8, 0.1] },
      },
    ],
  },
  {
    id: 'mastigacao_v3',
    title: 'Músculos da Mastigação e Nervo V3',
    subtitle: 'Controle motor da mandíbula pelo trigêmeo',
    region: 'cabeca',
    steps: [
      {
        title: 'O Nervo Mandibular (V3)',
        text: 'Terceiro ramo do nervo trigêmeo (V). É o único ramo misto (motor e sensitivo), saindo do crânio pelo forame oval para inervar os quatro músculos da mastigação, além do milo-hióideo e ventre anterior do digástrico.',
        dissect: 4,
        region: 'cabeca',
        highlight: 'n_mandibular',
        cam: { pos: [1.8, -0.2, 3.0], target: [0.3, -0.6, 0.2] },
      },
      {
        title: 'Músculo Masseter',
        text: 'Músculo retangular espesso estendido do arco zigomático ao ângulo da mandíbula. Poderoso elevador da mandíbula para trituração dos alimentos. Inervado pelo nervo massetérico de V3.',
        dissect: 3,
        region: 'cabeca',
        highlight: 'masseter',
        cam: { pos: [2.0, -0.3, 2.5], target: [0.4, -0.6, 0.3] },
      },
      {
        title: 'Músculo Temporal',
        text: 'Amplo músculo em leque que ocupa a fossa temporal e insere-se no processo coronoide da mandíbula. Suas fibras anteriores elevam a mandíbula; as posteriores a retrai (retrusão). Inervado pelos nervos temporais profundos de V3.',
        dissect: 3,
        region: 'cabeca',
        highlight: 'temporal',
        cam: { pos: [2.2, 0.2, 1.8], target: [0.3, -0.3, 0.1] },
      },
      {
        title: 'Pterigóideos Medial e Lateral',
        text: 'Profundos ao ramo da mandíbula. O pterigóideo medial eleva a mandíbula; o lateral a projeta anteriormente (protusão) e abre a boca ao puxar a cápsula e o disco da ATM.',
        dissect: 4,
        region: 'cabeca',
        highlight: 'pterigoideo_lateral',
        cam: { pos: [1.6, -0.4, 2.2], target: [0.3, -0.6, 0.2] },
      },
    ],
  },
  {
    id: 'facial_mimica',
    title: 'Nervo Facial (VII) e Mímica',
    subtitle: 'Expressão facial e ramos através da parótida',
    region: 'cabeca',
    steps: [
      {
        title: 'Origem e Saída pelo Forame Estilomastoideo',
        text: 'O VII par craniano emerge do tronco encefálico, percorre o canal facial no osso temporal e sai na base do crânio pelo forame estilomastoideo, penetrando na glândula parótida onde se ramifica.',
        dissect: 4,
        region: 'cabeca',
        highlight: 'n_facial',
        cam: { pos: [2.0, -0.3, 1.5], target: [0.3, -0.5, 0.0] },
      },
      {
        title: 'Cinco Grupos de Ramos Motores',
        text: 'Forma o plexo parotídeo que origina cinco grupos: Temporais (sobrancelhas/fronte), Zigomáticos (olhos), Bucais (bochechas/lábio superior), Marginal da mandíbula (lábio inferior) e Cervical (platisma).',
        dissect: 3,
        region: 'cabeca',
        highlight: 'platisma',
        cam: { pos: [1.9, -0.4, 2.8], target: [0.2, -0.7, 0.3] },
      },
      {
        title: 'Esfíncteres da Face: Olho e Boca',
        text: 'O orbicular do olho fecha as pálpebras firmemente (proteção corneana). O orbicular da boca fecha e protrui os lábios. Ambos dependem da integridade do nervo facial.',
        dissect: 2,
        region: 'cabeca',
        highlight: 'orbicular_olho',
        cam: { pos: [1.5, 0.0, 3.5], target: [0.0, -0.4, 0.5] },
      },
      {
        title: 'Correlação Clínica: Paralisia de Bell',
        text: 'A lesão periférica do nervo facial causa assimetria facial completa ipsilateral: perda das rugas na fronte, lagoftalmo (olho que não fecha) e queda do ângulo da boca com desvio para o lado sadio.',
        dissect: 2,
        region: 'cabeca',
        highlight: 'frontal',
        cam: { pos: [1.6, 0.3, 3.2], target: [0.0, -0.2, 0.4] },
      },
    ],
  },
  {
    id: 'parede_abdominal',
    title: 'Parede Abdominal e Inervação',
    subtitle: 'Camadas musculares, aponeuroses e nervos tóraco-abdominais',
    region: 'tronco',
    steps: [
      {
        title: 'Músculo Oblíquo Externo',
        text: 'A camada mais superficial. Suas fibras descem ântero-inferiormente ("mãos nos bolsos"). Sua aponeurose contribui para a linha alba e forma o ligamento inguinal inferiormente.',
        dissect: 2,
        region: 'tronco',
        highlight: 'obliquo_externo',
        cam: { pos: [2.2, -1.8, 4.5], target: [0.4, -2.6, 0.2] },
      },
      {
        title: 'Músculo Oblíquo Interno',
        text: 'Camada intermediária com fibras perpendiculares ao oblíquo externo (subindo ânpero-superiormente). Aumenta a pressão intra-abdominal e flete/gira o tronco.',
        dissect: 3,
        region: 'tronco',
        highlight: 'obliquo_interno',
        cam: { pos: [2.0, -2.0, 4.2], target: [0.4, -2.8, 0.2] },
      },
      {
        title: 'Transverso do Abdome',
        text: 'A camada profunda da parede ântero-lateral, com fibras horizontais como uma cinta natural. Crucial para a estabilização lombar e sustentação das vísceras abdominais.',
        dissect: 4,
        region: 'tronco',
        highlight: 'transverso_abd',
        cam: { pos: [1.8, -2.2, 3.8], target: [0.3, -2.9, 0.2] },
      },
      {
        title: 'Reto do Abdome e Linha Alba',
        text: 'Músculo vertical poligástrico anterior dividido por 3–4 interseções tendíneas e envolto pela bainha dos retos. Inervado pelos nervos intercostais inferiores (T7–T12).',
        dissect: 2,
        region: 'tronco',
        highlight: 'reto_abd',
        cam: { pos: [1.5, -2.0, 4.8], target: [0.0, -2.7, 0.4] },
      },
    ],
  },
];
