/**
 * Tours guiados didáticos passo a passo (F1.8).
 *
 * Cada passo define região, nível de dissecação, a estrutura em destaque (`highlight`, um id do catálogo) e o lado de
 * onde olhar (`view`: front | back | left | right | three). A câmera é enquadrada sozinha na estrutura; sem
 * `highlight`, mostra a região inteira. Os ids e as vistas são conferidos por `npm run test:catalog`.
 */
export const TOUR_VIEWS = ['front', 'back', 'left', 'right', 'three'];


export const TOURS = [
  {
    id: 'manguito',
    title: 'Manguito Rotador',
    subtitle: 'Estabilidade dinâmica e mobilidade do ombro',
    description: 'Os quatro músculos que mantêm a cabeça do úmero na cavidade glenoidal: origem, inserção, ação e nervo de cada um.',
    region: 'membro_sup',
    steps: [
      {
        title: 'Visão Geral do Manguito Rotador',
        text: 'O manguito rotador é formado por quatro músculos que abraçam a cabeça do úmero, estabilizando-a na cavidade glenoidal da escápula: supraespinal, infraespinal, redondo menor e subescapular.',
        dissect: 2,
        region: 'membro_sup',
        view: 'three',
      },
      {
        title: 'Músculo Supraespinal',
        text: 'Origina-se na fossa supraespinal da escápula e insere-se na faceta superior do tubérculo maior do úmero. Inicia a abdução do braço e colabora com o deltoide durante o movimento (a descrição clássica fala nos primeiros 15°, mas ele atua em toda a amplitude). Seu tendão é o mais acometido por tendinopatias e rupturas, em geral por compressão sob o arco coracoacromial.',
        dissect: 3,
        region: 'membro_sup',
        highlight: 'supraespinal',
        view: 'back',
      },
      {
        title: 'Músculo Infraespinal',
        text: 'Ocupa a fossa infraespinal e fixa-se na faceta média do tubérculo maior. É o principal rotador lateral do braço. Inervado pelo nervo supraescapular (C5, C6).',
        dissect: 3,
        region: 'membro_sup',
        highlight: 'infraespinal',
        view: 'back',
      },
      {
        title: 'Músculo Redondo Menor',
        text: 'Pequeno músculo tubular abaixo do infraespinal. Realiza rotação lateral e adução fraca do braço. Diferencia-se por ser inervado pelo nervo axilar (C5, C6).',
        dissect: 3,
        region: 'membro_sup',
        highlight: 'redondo_menor',
        view: 'back',
      },
      {
        title: 'Músculo Subescapular',
        text: 'Ocupa toda a fossa subescapular (face anterior da escápula) e insere-se no tubérculo menor do úmero. É um poderoso rotador medial e adutor do braço, inervado pelos nervos subescapulares superior e inferior.',
        dissect: 4,
        region: 'membro_sup',
        highlight: 'subescapular',
        view: 'front',
      },
    ],
  },
  {
    id: 'plexo_braquial',
    title: 'Plexo Braquial',
    subtitle: 'Origem e distribuição da inervação do membro superior',
    description: 'Das raízes C5–T1 aos cinco nervos terminais que inervam o membro superior.',
    region: 'membro_sup',
    steps: [
      {
        title: 'Formação das Raízes (C5–T1)',
        text: 'O plexo braquial é formado pelos ramos ventrais dos nervos espinais C5 a T1. Emerge no pescoço entre os músculos escalenos anterior e médio (trígono interescalênico).',
        dissect: 4,
        region: 'membro_sup',
        highlight: 'n_plexo_braquial',
        view: 'front',
      },
      {
        title: 'Troncos e Fascículos',
        text: 'As raízes unem-se em três troncos (superior, médio e inferior) que cruzam a clavícula, dividem-se em divisões anteriores e posteriores e formam os fascículos lateral, medial e posterior ao redor da artéria axilar.',
        dissect: 4,
        region: 'membro_sup',
        highlight: 'n_mediano',
        view: 'front',
      },
      {
        title: 'Ramos Terminais Principais',
        text: 'Origina os cinco grandes nervos terminais: Musculocutâneo (flexores do braço), Axilar (deltoide e redondo menor), Radial (extensores do membro), Mediano (maioria dos flexores do antebraço e eminência tenar) e Ulnar (flexor ulnar do carpo, metade medial do flexor profundo dos dedos e a maioria dos intrínsecos da mão).',
        dissect: 4,
        region: 'membro_sup',
        highlight: 'n_radial',
        view: 'front',
      },
    ],
  },
  {
    id: 'nervo_radial',
    title: 'Nervo Radial e Extensores',
    subtitle: 'Trajeto no sulco espiral e controle da extensão',
    description: 'Trajeto do nervo radial, músculos que ele inerva e o quadro clínico da queda do punho.',
    region: 'membro_sup',
    steps: [
      {
        title: 'Origem e Sulco do Nervo Radial',
        text: 'Maior ramo do fascículo posterior (C5–T1). Contorna o úmero posteriormente no sulco do nervo radial, acompanhado pela artéria braquial profunda, passando entre as cabeças lateral e medial do tríceps braquial.',
        dissect: 4,
        region: 'membro_sup',
        highlight: 'n_radial',
        view: 'back',
      },
      {
        title: 'Tríceps Braquial',
        text: 'Inervado pelo nervo radial antes de passar o cotovelo. Suas três cabeças (longa, lateral e medial) convergem para o olécrano da ulna, sendo o principal extensor do antebraço.',
        dissect: 3,
        region: 'membro_sup',
        highlight: 'triceps_lateral',
        view: 'back',
      },
      {
        title: 'Divisão no Antebraço: Ramos Profundo e Superficial',
        text: 'No cotovelo anterior, divide-se em ramo profundo (motor, atravessa o supinador como nervo interósseo posterior para os extensores de punho e dedos) e ramo superficial (puramente sensitivo para o dorso da mão).',
        dissect: 4,
        region: 'membro_sup',
        highlight: 'braquiorradial',
        view: 'front',
      },
      {
        title: 'Correlação Clínica: "Queda do Punho"',
        text: 'Fraturas da diáfise umeral ou compressão prolongada do nervo radial ("paralisia de sábado à noite") causam paralisia dos extensores do punho e dos dedos, resultando na mão caída.',
        dissect: 3,
        region: 'membro_sup',
        highlight: 'ecrl',
        view: 'left',
      },
    ],
  },
  {
    id: 'mastigacao_v3',
    title: 'Músculos da Mastigação e Nervo V3',
    subtitle: 'Controle motor da mandíbula pelo trigêmeo',
    description: 'Masseter, temporal e pterigóideos: o que cada um faz e como o ramo mandibular os inerva.',
    region: 'cabeca',
    steps: [
      {
        title: 'O Nervo Mandibular (V3)',
        text: 'Terceiro ramo do nervo trigêmeo (V). É o único ramo misto (motor e sensitivo), saindo do crânio pelo forame oval para inervar os quatro músculos da mastigação, além do milo-hióideo e ventre anterior do digástrico.',
        dissect: 4,
        region: 'cabeca',
        highlight: 'n_mandibular',
        view: 'left',
      },
      {
        title: 'Músculo Masseter',
        text: 'Músculo retangular espesso estendido do arco zigomático ao ângulo da mandíbula. Poderoso elevador da mandíbula para trituração dos alimentos. Inervado pelo nervo massetérico de V3.',
        dissect: 3,
        region: 'cabeca',
        highlight: 'masseter',
        view: 'left',
      },
      {
        title: 'Músculo Temporal',
        text: 'Amplo músculo em leque que ocupa a fossa temporal e insere-se no processo coronoide da mandíbula. Suas fibras anteriores elevam a mandíbula; as posteriores a retrai (retrusão). Inervado pelos nervos temporais profundos de V3.',
        dissect: 3,
        region: 'cabeca',
        highlight: 'temporal',
        view: 'left',
      },
      {
        title: 'Pterigóideos Medial e Lateral',
        text: 'Profundos ao ramo da mandíbula. O pterigóideo medial eleva a mandíbula; o lateral a projeta anteriormente (protusão) e abre a boca ao puxar a cápsula e o disco da ATM.',
        dissect: 4,
        region: 'cabeca',
        highlight: 'pterigoideo_lateral',
        view: 'left',
      },
    ],
  },
  {
    id: 'facial_mimica',
    title: 'Nervo Facial (VII) e Mímica',
    subtitle: 'Expressão facial e ramos através da parótida',
    description: 'Do forame estilomastoideo aos músculos da mímica, e o que acontece na paralisia de Bell.',
    region: 'cabeca',
    steps: [
      {
        title: 'Origem e Saída pelo Forame Estilomastoideo',
        text: 'O VII par craniano emerge do tronco encefálico, percorre o canal facial no osso temporal e sai na base do crânio pelo forame estilomastoideo, penetrando na glândula parótida onde se ramifica.',
        dissect: 4,
        region: 'cabeca',
        highlight: 'n_facial',
        view: 'left',
      },
      {
        title: 'Cinco Grupos de Ramos Motores',
        text: 'Forma o plexo parotídeo que origina cinco grupos: Temporais (sobrancelhas/fronte), Zigomáticos (olhos), Bucais (bochechas/lábio superior), Marginal da mandíbula (lábio inferior) e Cervical (platisma).',
        dissect: 3,
        region: 'cabeca',
        highlight: 'platisma',
        view: 'three',
      },
      {
        title: 'Esfíncteres da Face: Olho e Boca',
        text: 'O orbicular do olho fecha as pálpebras firmemente (proteção corneana). O orbicular da boca fecha e protrui os lábios. Ambos dependem da integridade do nervo facial.',
        dissect: 2,
        region: 'cabeca',
        highlight: 'orbicular_olho',
        view: 'front',
      },
      {
        title: 'Correlação Clínica: Paralisia de Bell',
        text: 'A lesão periférica do nervo facial causa assimetria facial completa ipsilateral: perda das rugas na fronte, lagoftalmo (olho que não fecha) e queda do ângulo da boca com desvio para o lado sadio.',
        dissect: 2,
        region: 'cabeca',
        highlight: 'frontal',
        view: 'front',
      },
    ],
  },
  {
    id: 'parede_abdominal',
    title: 'Parede Abdominal e Inervação',
    subtitle: 'Camadas musculares, aponeuroses e nervos tóraco-abdominais',
    description: 'Os músculos da parede ântero-lateral do abdome, do mais superficial ao mais profundo.',
    region: 'tronco',
    steps: [
      {
        title: 'Músculo Oblíquo Externo',
        text: 'A camada mais superficial. Suas fibras descem ântero-inferiormente ("mãos nos bolsos"). Sua aponeurose contribui para a linha alba e forma o ligamento inguinal inferiormente.',
        dissect: 2,
        region: 'tronco',
        highlight: 'obliquo_externo',
        view: 'front',
      },
      {
        title: 'Músculo Oblíquo Interno',
        text: 'Camada intermediária com fibras perpendiculares ao oblíquo externo (subindo ântero-superiormente). Aumenta a pressão intra-abdominal e flete/gira o tronco.',
        dissect: 3,
        region: 'tronco',
        highlight: 'obliquo_interno',
        view: 'front',
      },
      {
        title: 'Transverso do Abdome',
        text: 'A camada profunda da parede ântero-lateral, com fibras horizontais como uma cinta natural. Crucial para a estabilização lombar e sustentação das vísceras abdominais.',
        dissect: 4,
        region: 'tronco',
        highlight: 'transverso_abdome',
        view: 'front',
      },
      {
        title: 'Reto do Abdome e Linha Alba',
        text: 'Músculo vertical poligástrico anterior dividido por 3–4 interseções tendíneas e envolto pela bainha dos retos. Inervado pelos nervos intercostais inferiores (T7–T12).',
        dissect: 2,
        region: 'tronco',
        highlight: 'reto_abdome',
        view: 'front',
      },
    ],
  },
];
